"""add api token

Revision ID: 2bd0f955d1d3
Revises: 6cd62168a5f4
Create Date: 2025-04-11 23:34:28.107336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '2bd0f955d1d3'
down_revision: Union[str, None] = '6cd62168a5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_announcement_reads_announcement_id_announcements', 'announcement_reads', type_='foreignkey')
    op.drop_constraint('fk_announcement_reads_username_users', 'announcement_reads', type_='foreignkey')
    op.create_foreign_key(op.f('fk_announcement_reads_announcement_id_announcements'), 'announcement_reads', 'announcements', ['announcement_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_announcement_reads_username_users'), 'announcement_reads', 'users', ['username'], ['username'], ondelete='CASCADE')
    op.drop_constraint('fk_user_preferences_background_id_images', 'user_preferences', type_='foreignkey')
    op.drop_constraint('fk_user_preferences_frame_id_images', 'user_preferences', type_='foreignkey')
    op.drop_constraint('fk_user_preferences_passname_id_images', 'user_preferences', type_='foreignkey')
    op.drop_constraint('fk_user_preferences_username_users', 'user_preferences', type_='foreignkey')
    op.drop_constraint('fk_user_preferences_character_id_images', 'user_preferences', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_preferences_passname_id_images'), 'user_preferences', 'images', ['passname_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_user_preferences_username_users'), 'user_preferences', 'users', ['username'], ['username'])
    op.create_foreign_key(op.f('fk_user_preferences_frame_id_images'), 'user_preferences', 'images', ['frame_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_user_preferences_character_id_images'), 'user_preferences', 'images', ['character_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_user_preferences_background_id_images'), 'user_preferences', 'images', ['background_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('api_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_users_api_token'), 'users', ['api_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_api_token'), table_name='users')
    op.drop_column('users', 'api_token')
    op.drop_constraint(op.f('fk_user_preferences_background_id_images'), 'user_preferences', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_preferences_character_id_images'), 'user_preferences', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_preferences_frame_id_images'), 'user_preferences', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_preferences_username_users'), 'user_preferences', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_preferences_passname_id_images'), 'user_preferences', type_='foreignkey')
    op.create_foreign_key('fk_user_preferences_character_id_images', 'user_preferences', 'images', ['character_id'], ['id'], onupdate='RESTRICT', ondelete='SET NULL')
    op.create_foreign_key('fk_user_preferences_username_users', 'user_preferences', 'users', ['username'], ['username'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('fk_user_preferences_passname_id_images', 'user_preferences', 'images', ['passname_id'], ['id'], onupdate='RESTRICT', ondelete='SET NULL')
    op.create_foreign_key('fk_user_preferences_frame_id_images', 'user_preferences', 'images', ['frame_id'], ['id'], onupdate='RESTRICT', ondelete='SET NULL')
    op.create_foreign_key('fk_user_preferences_background_id_images', 'user_preferences', 'images', ['background_id'], ['id'], onupdate='RESTRICT', ondelete='SET NULL')
    op.drop_constraint(op.f('fk_announcement_reads_username_users'), 'announcement_reads', type_='foreignkey')
    op.drop_constraint(op.f('fk_announcement_reads_announcement_id_announcements'), 'announcement_reads', type_='foreignkey')
    op.create_foreign_key('fk_announcement_reads_username_users', 'announcement_reads', 'users', ['username'], ['username'], onupdate='RESTRICT', ondelete='CASCADE')
    op.create_foreign_key('fk_announcement_reads_announcement_id_announcements', 'announcement_reads', 'announcements', ['announcement_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    # ### end Alembic commands ###
