"""init database

Revision ID: 9cdcf6f8ca8c
Revises: 
Create Date: 2025-02-26 22:57:46.666175

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "9cdcf6f8ca8c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "images",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sega_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("uploaded_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_images_sega_name"), "images", ["sega_name"], unique=False)
    op.create_table(
        "user_accounts",
        sa.Column("account_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("account_server", sa.Enum("DIVING_FISH", "LXNS", "WECHAT", name="accountserver"), nullable=False),
        sa.Column("account_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("nickname", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bind_qq", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("player_rating", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("account_name", "account_server"),
    )
    op.create_index(op.f("ix_user_accounts_username"), "user_accounts", ["username"], unique=False)
    op.create_table(
        "users",
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prefer_server", sa.Enum("DIVING_FISH", "LXNS", "WECHAT", name="accountserver"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("username"),
    )
    op.create_table(
        "user_preferences",
        sa.Column("maimai_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("simplified_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("character_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("friend_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("dx_rating", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("qr_size", sa.Integer(), nullable=False),
        sa.Column("mask_type", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("character_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("background_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("frame_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("passname_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["background_id"],
            ["images.id"],
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["images.id"],
        ),
        sa.ForeignKeyConstraint(
            ["frame_id"],
            ["images.id"],
        ),
        sa.ForeignKeyConstraint(
            ["passname_id"],
            ["images.id"],
        ),
        sa.PrimaryKeyConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_preferences")
    op.drop_table("users")
    op.drop_index(op.f("ix_user_accounts_username"), table_name="user_accounts")
    op.drop_table("user_accounts")
    op.drop_index(op.f("ix_images_sega_name"), table_name="images")
    op.drop_table("images")
    # ### end Alembic commands ###
