"""add wahlap player fields

Revision ID: d89e6f4b3a2c
Revises: c135931c4bc8
Create Date: 2025-08-19 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'd89e6f4b3a2c'
down_revision: Union[str, None] = 'c135931c4bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('wahlap_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_accounts', sa.Column('wahlap_friend_code', sa.Integer(), nullable=True))
    op.add_column('user_preferences', sa.Column('player_name_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='prober'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'player_name_source')
    op.drop_column('user_accounts', 'wahlap_friend_code')
    op.drop_column('user_accounts', 'wahlap_name')
    # ### end Alembic commands ###
