"""add card features

Revision ID: e942f8167a6e
Revises: 9cdcf6f8ca8c
Create Date: 2025-03-25 19:47:51.254547

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "e942f8167a6e"
down_revision: Union[str, None] = "9cdcf6f8ca8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "card_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("credentials", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("player_rating", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_accounts")),
    )
    op.create_index(op.f("ix_card_accounts_credentials"), "card_accounts", ["credentials"], unique=True)
    op.create_table(
        "card_scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("level_index", sa.Enum("BASIC", "ADVANCED", "EXPERT", "MASTER", "ReMASTER", name="levelindex"), nullable=False),
        sa.Column("achievements", sa.Float(), nullable=True),
        sa.Column("fc", sa.Enum("APP", "AP", "FCP", "FC", name="fctype"), nullable=True),
        sa.Column("fs", sa.Enum("SYNC", "FS", "FSP", "FSD", "FSDP", name="fstype"), nullable=True),
        sa.Column("dx_score", sa.Integer(), nullable=True),
        sa.Column("dx_rating", sa.Float(), nullable=True),
        sa.Column(
            "rate", sa.Enum("SSSP", "SSS", "SSP", "SS", "SP", "S", "AAA", "AA", "A", "BBB", "BB", "B", "C", "D", name="ratetype"), nullable=False
        ),
        sa.Column("type", sa.Enum("STANDARD", "DX", "UTAGE", name="songtype"), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["card_accounts.id"], name=op.f("fk_card_scores_account_id_card_accounts"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_scores")),
    )
    op.create_index(op.f("ix_card_scores_account_id"), "card_scores", ["account_id"], unique=False)
    op.create_index(op.f("ix_card_scores_song_id"), "card_scores", ["song_id"], unique=False)
    op.create_table(
        "cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sa.Enum("DRAFTED", "SCHEDULED", "CONFIRMED", "ACTIVATED", name="cardstatus"), nullable=False),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["card_accounts.id"], name=op.f("fk_cards_account_id_card_accounts"), ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cards")),
    )
    op.create_index(op.f("ix_cards_phone"), "cards", ["phone"], unique=False)
    op.create_index(op.f("ix_cards_uuid"), "cards", ["uuid"], unique=True)
    op.create_table(
        "card_preferences",
        sa.Column("maimai_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("simplified_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("character_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("friend_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("dx_rating", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("qr_size", sa.Integer(), nullable=False),
        sa.Column("mask_type", sa.Integer(), nullable=False),
        sa.Column("uuid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("character_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("background_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("frame_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("passname_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["background_id"], ["images.id"], name=op.f("fk_card_preferences_background_id_images"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["character_id"], ["images.id"], name=op.f("fk_card_preferences_character_id_images"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["frame_id"], ["images.id"], name=op.f("fk_card_preferences_frame_id_images"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["passname_id"], ["images.id"], name=op.f("fk_card_preferences_passname_id_images"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["uuid"], ["cards.uuid"], name=op.f("fk_card_preferences_uuid_cards"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_card_preferences")),
    )
    op.drop_constraint("user_preferences_ibfk_1", "user_preferences", type_="foreignkey")
    op.drop_constraint("user_preferences_ibfk_5", "user_preferences", type_="foreignkey")
    op.drop_constraint("user_preferences_ibfk_4", "user_preferences", type_="foreignkey")
    op.drop_constraint("user_preferences_ibfk_3", "user_preferences", type_="foreignkey")
    op.drop_constraint("user_preferences_ibfk_2", "user_preferences", type_="foreignkey")
    op.create_foreign_key(op.f("fk_user_preferences_username_users"), "user_preferences", "users", ["username"], ["username"])
    op.create_foreign_key(
        op.f("fk_user_preferences_background_id_images"), "user_preferences", "images", ["background_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(op.f("fk_user_preferences_passname_id_images"), "user_preferences", "images", ["passname_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(
        op.f("fk_user_preferences_character_id_images"), "user_preferences", "images", ["character_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(op.f("fk_user_preferences_frame_id_images"), "user_preferences", "images", ["frame_id"], ["id"], ondelete="SET NULL")
    op.add_column("users", sa.Column("privilege", sa.Enum("BANNED", "NORMAL", "ADMIN", name="privilege"), server_default="NORMAL", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "privilege")
    op.drop_constraint(op.f("fk_user_preferences_frame_id_images"), "user_preferences", type_="foreignkey")
    op.drop_constraint(op.f("fk_user_preferences_character_id_images"), "user_preferences", type_="foreignkey")
    op.drop_constraint(op.f("fk_user_preferences_passname_id_images"), "user_preferences", type_="foreignkey")
    op.drop_constraint(op.f("fk_user_preferences_background_id_images"), "user_preferences", type_="foreignkey")
    op.drop_constraint(op.f("fk_user_preferences_username_users"), "user_preferences", type_="foreignkey")
    op.create_foreign_key(
        "user_preferences_ibfk_2", "user_preferences", "users", ["username"], ["username"], onupdate="RESTRICT", ondelete="RESTRICT"
    )
    op.create_foreign_key("user_preferences_ibfk_3", "user_preferences", "images", ["frame_id"], ["id"], onupdate="RESTRICT", ondelete="SET NULL")
    op.create_foreign_key("user_preferences_ibfk_4", "user_preferences", "images", ["character_id"], ["id"], onupdate="RESTRICT", ondelete="SET NULL")
    op.create_foreign_key("user_preferences_ibfk_5", "user_preferences", "images", ["passname_id"], ["id"], onupdate="RESTRICT", ondelete="SET NULL")
    op.create_foreign_key(
        "user_preferences_ibfk_1", "user_preferences", "images", ["background_id"], ["id"], onupdate="RESTRICT", ondelete="SET NULL"
    )
    op.drop_table("card_preferences")
    op.drop_table("cards")
    op.drop_table("card_scores")
    op.drop_table("card_accounts")
    # ### end Alembic commands ###
