"""add card pass binding

Revision ID: fabb6c899d98
Revises: dd0c9bfac74a
Create Date: 2025-03-19 15:00:48.293213

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "fabb6c899d98"
down_revision: Union[str, None] = "dd0c9bfac74a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("card_preferences", sa.Column("skip_activation", sa.Boolean(), nullable=False))
    op.add_column("card_preferences", sa.Column("protect_card", sa.Boolean(), nullable=False))
    op.drop_constraint("card_preferences_ibfk_4", "card_preferences", type_="foreignkey")
    op.drop_constraint("card_preferences_ibfk_5", "card_preferences", type_="foreignkey")
    op.drop_constraint("card_preferences_ibfk_3", "card_preferences", type_="foreignkey")
    op.drop_constraint("card_preferences_ibfk_1", "card_preferences", type_="foreignkey")
    op.drop_constraint("card_preferences_ibfk_2", "card_preferences", type_="foreignkey")
    op.create_foreign_key(None, "card_preferences", "images", ["passname_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(None, "card_preferences", "images", ["frame_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(None, "card_preferences", "images", ["character_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(None, "card_preferences", "images", ["background_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(None, "card_preferences", "cards", ["uuid"], ["uuid"], ondelete="CASCADE")
    op.add_column("cards", sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint("cards_ibfk_1", "cards", type_="foreignkey")
    op.create_foreign_key(None, "cards", "users", ["username"], ["username"], ondelete="SET NULL")
    op.create_foreign_key(None, "cards", "card_users", ["user_id"], ["id"], ondelete="SET NULL")
    op.drop_constraint("scores_ibfk_1", "scores", type_="foreignkey")
    op.create_foreign_key(None, "scores", "card_users", ["user_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint("user_preferences_ibfk_10", "user_preferences", type_="foreignkey")
    op.drop_constraint("user_preferences_ibfk_6", "user_preferences", type_="foreignkey")
    op.drop_constraint("user_preferences_ibfk_9", "user_preferences", type_="foreignkey")
    op.drop_constraint("user_preferences_ibfk_7", "user_preferences", type_="foreignkey")
    op.drop_constraint("user_preferences_ibfk_8", "user_preferences", type_="foreignkey")
    op.create_foreign_key(None, "user_preferences", "images", ["character_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(None, "user_preferences", "images", ["background_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(None, "user_preferences", "images", ["frame_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(None, "user_preferences", "users", ["username"], ["username"])
    op.create_foreign_key(None, "user_preferences", "images", ["passname_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_preferences", type_="foreignkey")
    op.drop_constraint(None, "user_preferences", type_="foreignkey")
    op.drop_constraint(None, "user_preferences", type_="foreignkey")
    op.drop_constraint(None, "user_preferences", type_="foreignkey")
    op.drop_constraint(None, "user_preferences", type_="foreignkey")
    op.create_foreign_key("user_preferences_ibfk_8", "user_preferences", "images", ["frame_id"], ["id"], onupdate="RESTRICT", ondelete="SET NULL")
    op.create_foreign_key(
        "user_preferences_ibfk_7", "user_preferences", "users", ["username"], ["username"], onupdate="RESTRICT", ondelete="RESTRICT"
    )
    op.create_foreign_key("user_preferences_ibfk_9", "user_preferences", "images", ["character_id"], ["id"], onupdate="RESTRICT", ondelete="SET NULL")
    op.create_foreign_key(
        "user_preferences_ibfk_6", "user_preferences", "images", ["background_id"], ["id"], onupdate="RESTRICT", ondelete="SET NULL"
    )
    op.create_foreign_key("user_preferences_ibfk_10", "user_preferences", "images", ["passname_id"], ["id"], onupdate="RESTRICT", ondelete="SET NULL")
    op.drop_constraint(None, "scores", type_="foreignkey")
    op.create_foreign_key("scores_ibfk_1", "scores", "card_users", ["user_id"], ["id"], onupdate="RESTRICT", ondelete="CASCADE")
    op.drop_constraint(None, "cards", type_="foreignkey")
    op.drop_constraint(None, "cards", type_="foreignkey")
    op.create_foreign_key("cards_ibfk_1", "cards", "card_users", ["user_id"], ["id"], onupdate="RESTRICT", ondelete="CASCADE")
    op.drop_column("cards", "username")
    op.drop_constraint(None, "card_preferences", type_="foreignkey")
    op.drop_constraint(None, "card_preferences", type_="foreignkey")
    op.drop_constraint(None, "card_preferences", type_="foreignkey")
    op.drop_constraint(None, "card_preferences", type_="foreignkey")
    op.drop_constraint(None, "card_preferences", type_="foreignkey")
    op.create_foreign_key("card_preferences_ibfk_2", "card_preferences", "images", ["character_id"], ["id"], onupdate="RESTRICT", ondelete="SET NULL")
    op.create_foreign_key(
        "card_preferences_ibfk_1", "card_preferences", "images", ["background_id"], ["id"], onupdate="RESTRICT", ondelete="SET NULL"
    )
    op.create_foreign_key("card_preferences_ibfk_3", "card_preferences", "images", ["frame_id"], ["id"], onupdate="RESTRICT", ondelete="SET NULL")
    op.create_foreign_key("card_preferences_ibfk_5", "card_preferences", "cards", ["uuid"], ["uuid"], onupdate="RESTRICT", ondelete="CASCADE")
    op.create_foreign_key("card_preferences_ibfk_4", "card_preferences", "images", ["passname_id"], ["id"], onupdate="RESTRICT", ondelete="SET NULL")
    op.drop_column("card_preferences", "protect_card")
    op.drop_column("card_preferences", "skip_activation")
    # ### end Alembic commands ###
