/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IArcticonsClash: typeof import('~icons/arcticons/clash')['default']
    IArcticonsClashMeta: typeof import('~icons/arcticons/clash-meta')['default']
    IBxsBalloon: typeof import('~icons/bxs/balloon')['default']
    IFa6SolidMagnifyingGlassLocation: typeof import('~icons/fa6-solid/magnifying-glass-location')['default']
    IIonMdRocket: typeof import('~icons/ion/md-rocket')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const IArcticonsClash: typeof import('~icons/arcticons/clash')['default']
  const IArcticonsClashMeta: typeof import('~icons/arcticons/clash-meta')['default']
  const IBxsBalloon: typeof import('~icons/bxs/balloon')['default']
  const IFa6SolidMagnifyingGlassLocation: typeof import('~icons/fa6-solid/magnifying-glass-location')['default']
  const IIonMdRocket: typeof import('~icons/ion/md-rocket')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}